services:
  mockserver:
    image: mockserver
    ports:
      - "9999:8080"
  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --project=abcall --host-port=0.0.0.0:8120
    ports:
      - "8120:8120"