services:
  mockserver:
    build:
      context: ./Mockserver
    ports:
      - "9999:8080"
  monitor:
    build:
      context: ./Monitor
    ports:
      - "5002:5002"
  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --project=abcall --host-port=0.0.0.0:8120
    ports:
      - "8120:8120"
  principal:
    build:
      context: GestorLlamadas/Principal
    ports:
      - "5003:5003"
  redundante:
    build:
      context: GestorLlamadas/Redundante
    ports:
      - "5004:5004"
  receptor:
    build:
      context: ./Receptor
    ports:
      - "5001:5001"
    depends_on:
      - mockserver
      - pubsub