#######################################################################################################################
### Creacion topico message
PUT http://localhost:{{puerto}}/v1/projects/{{id-proyecto}}/topics/message

### Creacion subscripcion message.gestor-llamadas-principal
PUT http://localhost:{{puerto}}/v1/projects/{{id-proyecto}}/subscriptions/message.{{gestor-llamadas-principal}}
Content-Type: application/json

{
  "topic": "projects/{{id-proyecto}}/topics/message"
}

### Creacion subscripcion message.gestor-llamadas-redundante
PUT http://localhost:{{puerto}}/v1/projects/{{id-proyecto}}/subscriptions/message.{{gestor-llamadas-redundante}}
Content-Type: application/json

{
  "topic": "projects/{{id-proyecto}}/topics/message"
}

#######################################################################################################################
### Creacion topico replies
PUT http://localhost:{{puerto}}/v1/projects/{{id-proyecto}}/topics/replies

### Creacion subscripcion replies.receptor
PUT http://localhost:{{puerto}}/v1/projects/{{id-proyecto}}/subscriptions/replies.{{receptor}}
Content-Type: application/json

{
  "topic": "projects/{{id-proyecto}}/topics/replies"
}